NewRepublique.Garofalo.Campaign/Models/ViewModels/PosterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewRepublique.Garofalo.Campaign.Models.ViewModels
{
    public class PosterViewModel
    {
        public int Id { get; set; }
        public int EntrantId { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public int Views { get; set; }
        public bool IsFlaggedForInappropriate { get; set; }
        public bool IsVisible { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ThumbnailUrl { get; set; }
        public int PreviousPosterId { get; set; }
        public int NextPosterId { get; set; }
        public string PosterUrlForFB { get; set; }
        public int Share { get; set; }

        public string AuthorName { get; set; }
    }
}

NewRepublique.Garofalo.Campaign/Models/ViewModels/PostersViewModel.cs
using NewRepublique.Garofalo.Campaign.Models.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewRepublique.Garofalo.Campaign.Models.ViewModels
{
    public class PostersViewModel
    {
        public IEnumerable<PosterModel> PostersToShow { get; set; }
        public int PageNumber { get; set; }
    }
}

NewRepublique.Garofalo.Campaign/Controllers/GalleryController.cs
using AutoMapper;
using NewRepublique.Data.Service;
using NewRepublique.Garofalo.Campaign.Models.DTOs;
using NewRepublique.Garofalo.Campaign.Models.ViewModels;
using NewRepublique.Infrastructure.Helpers;
using NewRepublique.PetaPoco.Repository.POCOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace NewRepublique.Garofalo.Campaign.Controllers
{
    public class GalleryController : Controller
    {
        private IPosterService _posterService;
        private IEmailHelper _emailHelper;
        public GalleryController(IPosterService posterService, IEmailHelper emailHelper)
        {
            _posterService = posterService;
            _emailHelper = emailHelper;
        }
        public ActionResult Index(string orderBy)
        {
            TempData["pageNumber"] = null;
            ViewBag.orderby = string.IsNullOrEmpty(orderBy) ? "mostRecent" : orderBy;
            ViewBag.posterid = 0;
            ViewBag.total = _posterService.GetPosterCount(true);
            return View();
        }

        public ActionResult ShowPoster(int? id, bool? autoDisplayModal)
        {
            ViewBag.total = _posterService.GetPosterCount(true);
            TempData["pageNumber"] = null;
            ViewBag.orderby = "mostRecent";
            ViewBag.posterid = 0;
            ViewBag.autodisplaymodal = false;

            if (id == null)
                return View("Index");
            else
            {                
                ViewBag.autodisplaymodal = true;
                ViewBag.posterid = id;               

                return View("Index");
            }
        }

        public ActionResult Posters(string orderBy)
        {
            try
            {
                var model = new PostersViewModel();
                int pageNumber = TempData["pageNumber"] == null ? 1 : int.Parse(TempData["pageNumber"].ToString());
                var order = string.IsNullOrEmpty(orderBy) ? "mostRecent" : orderBy;
                ViewBag.orderby = order;
                var result = GetPosters(order, pageNumber);

                model.PostersToShow = result;
                model.PageNumber = pageNumber;
                pageNumber = pageNumber + 1;

                TempData["pageNumber"] = pageNumber;
                ViewBag.orderby = orderBy;
                

                return View("_Posters", model);
            }
            catch(Exception ex)
            {
                StringBuilder sb = new StringBuilder();
                sb.AppendLine(ex.Message);
                sb.AppendLine(", Stacktrace: ");
                sb.AppendLine(ex.StackTrace);

                _emailHelper.SendEmail(ConfigurationHelper.Instance.FromErrorEmail, ConfigurationHelper.Instance.ToErrorEmail, sb.ToString(), "Error: Garofalo Poster Website - Gallery");

                return PartialView("_Error");
            }            
        }

        public IEnumerable<PosterModel> GetPosters(string order, int pageNumber)
        { 
            if(order == "mostRecent")
            {
                return Mapper.Map<IEnumerable<Poster>, IEnumerable<PosterModel>>
                (_posterService.GetPostersForGalleryOrderByCreateDate(pageNumber, 3, true));
            }
            else
            {
                return Mapper.Map<IEnumerable<Poster>, IEnumerable<PosterModel>>
                (_posterService.GetPostersForGalleryOrderByViews(pageNumber, 3, true));
            }
        }

        public PartialViewResult GetPoster(int id, string orderBy)
        {
            try
            {
                var result = _posterService.GetById(id);
                if (result != null)
                {
                    var poster = Mapper.Map<Poster, PosterModel>(result);

                    if(!poster.IsVisible)
                    {
                        ViewBag.showerror = 1;
                        return PartialView("_ModalPoster");
                    }

                    result.Views = poster.Views + 1;
                    _posterService.Update(result);

                    var posterViewModel = new PosterViewModel()
                    {
                        CreatedOn = poster.CreatedOn,
                        EntrantId = poster.EntrantId,
                        Id = poster.Id,
                        ImageUrl = poster.ImageUrl,
                        IsFlaggedForInappropriate = poster.IsFlaggedForInappropriate,
                        IsVisible = poster.IsVisible,
                        ModifiedBy = poster.ModifiedBy,
                        ModifiedOn = poster.ModifiedOn,
                        Title = poster.Title,
                        Views = poster.Views,
                        AuthorName = poster.Entrant.FirstName
                    };

                    PosterModalModel pmm = new PosterModalModel();

                    if (orderBy == "mostRecent")
                    {
                        pmm = Mapper.Map<PosterModalCreatedOn, PosterModalModel>(_posterService.GetPreviousAndNextPosterIdsOrderByCreatedOnDesc(id).FirstOrDefault());
                    }
                    else
                    {
                        pmm = Mapper.Map<PosterModalViews, PosterModalModel>(_posterService.GetPreviousAndNextPosterIdsOrderByViewsDesc(id).FirstOrDefault());
                    }

                    posterViewModel.PreviousPosterId = pmm.PreviousValue;
                    posterViewModel.NextPosterId = pmm.NextValue;
                    
                    //Original
                    var posterUrlForFB = string.Format("{0}://{1}/Gallery/ShowPoster?id={2}&autoDisplayModal=true", Request.Url.Scheme, Request.Url.Authority, id);

                    //var posterUrlForFB = string.Format("{0}://{1}/Gallery/Show?id={2}", Request.Url.Scheme, Request.Url.Authority, id);
                    
                    posterViewModel.PosterUrlForFB = posterUrlForFB;
                    ViewBag.posterurlforfb = posterUrlForFB;
                    ViewBag.imageurlfromcdn = poster.ImageUrl;
                    ViewBag.thumbnail = poster.ThumbnailUrl;
                    ViewBag.imageforfb = poster.ImageUrl.Replace("thumbnail", "fb");
                    ViewBag.orderby = orderBy;

                    ViewBag.skunk = string.Format("https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fec2-54-79-1-210.ap-southeast-2.compute.amazonaws.com%2FGallery%2FShow%3Fid%3D{0}", id);

                    return PartialView("_ModalPoster", posterViewModel);
                }
                else
                    return PartialView("_ModalPoster");
            }
            catch (Exception ex)
            {
                StringBuilder sb = new StringBuilder();
                sb.AppendLine(ex.Message);
                sb.AppendLine(", Stacktrace: ");
                sb.AppendLine(ex.StackTrace);

                _emailHelper.SendEmail(ConfigurationHelper.Instance.FromErrorEmail, ConfigurationHelper.Instance.ToErrorEmail, sb.ToString(), "Error: Garofalo Poster Website - Gallery");

                return PartialView("_Error");
            }             
        }

        public PartialViewResult FlagForInappropriateness(int id)
        {
            try
            {
                var result = _posterService.GetById(id);
                if (result != null)
                {
                    result.IsFlaggedForInappropriate = true;
                    result.ModifiedOn = DateTime.Now;
                    var updateResult = _posterService.Update(result);

                    if (updateResult > 0)
                    {
                        ViewBag.flagmessage = "Poster has been flagged";
                    }
                    else
                    {
                        ViewBag.flagmessage = "An error occurred trying to flag this poster.";
                    }
                }
                else
                {
                    ViewBag.flagmessage = "An error occurred trying to flag this poster.";
                }
            }
            catch (Exception ex)
            {
                StringBuilder sb = new StringBuilder();
                sb.AppendLine(ex.Message);
                sb.AppendLine(", Stacktrace: ");
                sb.AppendLine(ex.StackTrace);

                _emailHelper.SendEmail(ConfigurationHelper.Instance.FromErrorEmail, ConfigurationHelper.Instance.ToErrorEmail, sb.ToString(), "Error: Garofalo Poster Website - Gallery");

                ViewBag.flagmessage = "An error occured while processing your request";
            }

            return PartialView("_Appropriateness");
        }

        public ActionResult Show(int id)
        {
            var model = new PosterViewModel();
            var result = _posterService.GetById(id);
            
            if (result != null)
            {
                ViewBag.url = string.Format("{0}://{1}/Gallery/ShowPoster?id={2}&autoDisplayModal=true", Request.Url.Scheme, Request.Url.Authority, id);
                ViewBag.imageurl = result.ImageUrl;
            }

            return View(model);
        }

        public ActionResult ShowTest()
        {
            return View();
        }
	}
}

NewRepublique.Garofalo.Campaign/Controllers/PosterController.cs
using AutoMapper;
using NewRepublique.Data.Service;
using NewRepublique.Garofalo.Campaign.Models.DTOs;
using NewRepublique.Garofalo.Campaign.Models.ViewModels;
using NewRepublique.PetaPoco.Repository.POCOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewRepublique.Garofalo.Campaign.Controllers
{
    public class PosterController : Controller
    {
        private IPosterService _posterService;

        public PosterController(IPosterService posterService)
        {
            _posterService = posterService;
        }

        public ActionResult Inspiration()
        {
            return View();
        }

        public ActionResult Filmnoir()
        {
            return View();
        }

        public ActionResult Tuscan()
        {
            return View();
        }

        public ActionResult Empire()
        {
            return View();
        }

        public ActionResult Romance()
        {
            return View();
        }

        public ActionResult RomCom()
        {
            return View();
        }

        public ActionResult Fantasy()
        {
            return View();
        }

        public ActionResult Final(string id)
        {
            var result = Mapper.Map<Poster, PosterModel>(_posterService.GetById(int.Parse(id)));

            ViewBag.imageurlfromcdn = result.ImageUrl;
            ViewBag.posterid = result.Id;
            ViewBag.thumbnail = result.ThumbnailUrl;
            ViewBag.posterurlforfb = string.Format("{0}://{1}/Gallery/ShowPoster?id={2}&autoDisplayModal=true", Request.Url.Scheme, Request.Url.Authority, result.Id);

            return View();
        }
	}
}

NewRepublique.Garofalo.Campaign/Views/Poster/Empire.cshtml
@{
    ViewBag.Title = "Empire";
    Layout = "~/Views/Poster/_BasePoster.cshtml";
}

<div class="col-9">

    <div class="workSpace empire original-workspace" id="empire">
        <div class="title-hotspot edit-text"></div>
        <div class="title">
            <span>The Empire</span>
        </div>



        <div class="hotspot-container" id="hotspot1" data-id="face-1">
            <div class="metaIcon" id="camera"></div>
            <div class="hotspot">
            </div>
        </div>
        <div class="hotspot-container" id="hotspot2" data-id="face-2">
            <div class="metaIcon" id="camera"></div>
            <div class="hotspot">
            </div>
        </div>
        <div class="hotspot-container" id="hotspot3" data-id="face-3">
            <div class="metaIcon" id="camera"></div>
            <div class="hotspot">
            </div>
        </div>
        <!--
        <div class="hotspot-container" id="hotspot3" data-id="face-3">
          <div class="metaIcon" id="camera"></div>
          <div class="hotspot">
          </div>
        </div>-->

        <div class="face" id="face1" data-id="face-1">
            <div class="icon">
                <a>Edit</a>
                <a>Cancel</a>
            </div>
            <img src="@Url.Content("~/Images/empire-face1.png")" alt="" class="face-1-original">
        </div>
        <div class="face-canvas face-1" id="canvas1">
            <img src="" class="face-1">
        </div>
        <div class="face" id="face2" data-id="face-2">
            <div class="icon">
                <a>Edit</a>
                <a>Cancel</a>
            </div>
            <img src="@Url.Content("~/Images/empire-face2.png")" alt="" class="face-2-original">
        </div>
        <div class="face-canvas face-2" id="canvas2">
            <img src="" class="face-2">
        </div>
        <div class="face" id="face3" data-id="face-3">
            <div class="icon">
                <a>Edit</a>
                <a>Cancel</a>
            </div>
            <img src="@Url.Content("~/Images/empire-face3.png")" alt="" class="face-3-original">
        </div>
        <div class="face-canvas face-3" id="canvas3">
            <img src="" class="face-3">
        </div>

        <div class="controls">
            <div class="scale">
                <!--<input type="range" id="image-scale" name="image-scale" min="0.5" max="3" value="1.0" step="0.015">-->
                <div class="sizing">
                    <a href="#" class="button barebones plus-minus minus-scale">-</a>
                    <a href="#" class="button barebones plus-minus add-scale">+</a>
                </div>
            </div>
            <div class="add">
                <a id="addEffect" onclick="addEffect(theDestination)" class="addToPoster">Add to Poster</a>
            </div>
        </div>
        <div class="poster">
            <img src="@Url.Content("~/Images/empire-poster.png")" alt="" id="thePoster">
        </div>
        <div class="marker">
            <img src="@Url.Content("~/Images/marker.png")" height="1140" width="806" alt="">
        </div>
    </div>
</div>

@section Scripts
{
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#text-editor-input').val("The Empire");
        });
    </script>
}

NewRepublique.Garofalo.Campaign/Views/Poster/Final.cshtml
@{
    ViewBag.Title = "Save and Share";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="flash"></div>
<div class="image-lightbox">
    <div class="image-container">
        <img src="" alt="" id="final-image">
    </div>
</div>
<div class="loading">
    <div class="loadContain">
        <img src="/images/loading.gif" alt="" class="loading-spin">
        <!--<div class="spinner">
          <div class="rect1"></div>
          <div class="rect2"></div>
          <div class="rect3"></div>
          <div class="rect4"></div>
          <div class="rect5"></div>
        </div>-->
        <p class="loadingMessage">Fear and Loading in Las Vegas...</p>
    </div>
</div> 
<div class="sidebar">
    <a class="closeSidebar"><img src="@Url.Content("~/Images/closeButton.png")" height="30" width="30" alt=""></a>
    <div class="row sidebarTop">
        <div class="large-12 columns">
            <a class="sidebar-back button">Back</a>
            <h2 class="sidebarTitle">Edit Face - <span class="currentSection">Insert an Image</span></h2>
        </div>
    </div>
    <div class="pickInput">
        <div class="input-method webcam-input">
            <div class="icon"></div>
            <h2>Take a Photo</h2>
        </div>
        <div class="divider">
            <img src="@Url.Content("~/Images/divider.png")" height="33" width="132" alt="">
        </div>
        <div class="input-method facebook-input">
            <div class="icon"></div>
            <h2>Choose from Facebook</h2>
        </div>
    </div>
    <div class="yourImages">
        <div class="row">
            <div class="large-12 columns">
                <div class="sidebarLoading">
                    <div class="spinner">
                        <div class="rect1"></div>
                        <div class="rect2"></div>
                        <div class="rect3"></div>
                        <div class="rect4"></div>
                        <div class="rect5"></div>
                    </div>
                </div>
                <ul class="photoPicker"></ul>
            </div>
        </div>
    </div>
    <div class="row sidebarButtons">
        <div class="buttonContain">
            <div class="col-6">
                <a href="@Url.Action("Index", "Gallery")" class="button large secondary">Cancel</a>
            </div>
            <div class="col-6">
                <a href="/editor.html" class="button large primary">
                    Save
                </a>
            </div>
        </div>
    </div>
</div>
<div class="blackOut"></div>
<div class="container">
    <div class="row">
        <header>
            <a href="/">
                <img src="@Url.Content("~/Images/logo.png")" height="79" width="208" alt="" class="center">
            </a>
            <div class="fbStatus">
                <p>Connected as <span class="myName"></span><a href="@Url.Action("Index", "Home")" class="logOut" onclick="FB.logout()">Log Out</a></p>
            </div>
        </header>
    </div>
    <div class="row">
        <div class="col-3">
            <div class="panel">
                <div class="steps">
                    <div class="step">
                        <div class="heading">
                            <div class="first line"><h4>1</h4></div>
                            <div class="second line"><h1>Pick Inspiration</h1></div>
                        </div>
                    </div>
                    <div class="step">
                        <div class="heading">
                            <div class="first line"><h4>2</h4></div>
                            <div class="second line"><h1>Design Your Poster</h1></div>
                        </div>
                    </div>
                    <div class="step active">
                        <div class="heading">
                            <div class="first line"><h4>3</h4></div>
                            <div class="second line"><h1>Save and Share</h1></div>
                            <p>Almost there - just share your genius on Facebook. It's looking like you may have a box-office smash on your hands.</p>
                            <a class="button medium secondary" href="@Url.Action("Index", "Gallery")">View Gallery</a><br>
                            <a class="button medium primary fbShare" onclick="finalSharePrompt(@ViewBag.posterid)">
                                <img src="@Url.Content("~/Images/fb.png")" height="20" width="20" alt="" class="icon">
                                Share your poster
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-9">
            <!-- poster goes here -->
            <div class="final-poster-frame">
                <div class="the-frame">
                    <img src="@Url.Content("~/Images/final-frame.png")" alt="">
                </div>
                <div class="the-poster">
                    <img src="@ViewBag.imageurlfromcdn" alt="">
                ></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-3">
    </div>
    <div class="col-9 renderDump">

    </div>
</div>
<div class="row">
    <div class="col-3">
    </div>
    <div class="col-9 finalDump">

    </div>
</div>

@section Scripts
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/pointer-fill.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/fb-ck.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/flexslider.js")"></script>

    <!-- Main App -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/app-ck.js")"></script>

    <!-- Editor Scripts -->
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
    <script src="@Url.Content("~/Scripts/html2canvas.js")"></script>
    <script src="@Url.Content("~/Scripts/slider.js")"></script>
    <script src="@Url.Content("~/Scripts/caman.js")"></script>
    <script src="@Url.Content("~/Scripts/scriptcam.min.js")"></script>
    <script src="@Url.Content("~/Scripts/getImage.js")"></script>
    <script src="@Url.Content("~/Scripts/squishy.js")"></script>
    <script src="@Url.Content("~/Scripts/editor.js")"></script>

    <script type="text/javascript">
        function finalSharePrompt(posterId) {
            FB.ui({
                method: 'feed',
                name: 'The Garofalo Gallery',
                picture: '@ViewBag.thumbnail',
                link: '@ViewBag.posterurlforfb',
                caption: 'now starring… you!',
                description: "Choose a movie poster, add yourself, customise the text and then faster than you can yell 'cut!', you're the star in your own movie."
            }, function (response) {
                if (response && !response.error_code) {
                    $.post("/api/UpdatePicture/Post", {
                        id: posterId
                    })
                    //alert('Posting completed.');
                } else {
                    //alert('Error while posting.');
                }
            });
        }
    </script>
}

NewRepublique.Garofalo.Campaign/Views/Poster/_BasePoster.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPoster.cshtml";
}

<div class="flash"></div>
<div class="title-editor">
    <div class="edit-box">
        <h2>Edit Text</h2>
        <span class="charRemaining"></span>
        <input type="text" id="text-editor-input" value="" autocomplete="off">
    </div>
    <div class="edit-buttons">
        <div class="row">
            <div class="col-6">
                <a class="button large secondary cancel-title">Cancel</a>
            </div>
            <div class="col-6">
                <a class="button large primary update-title">Update Title</a>
            </div>
        </div>
    </div>
</div>
<div class="cast-editor">
    <div class="edit-box">
        <h2>First Name</h2>
        <span class="firstRemaining"></span>
        <input type="text" id="first-name-input" value="" autocomplete="off">
        <h2>Last Name</h2>
        <span class="lastRemaining"></span>
        <input type="text" id="last-name-input" value="" autocomplete="off">
    </div>
    <div class="edit-buttons">
        <div class="row">
            <div class="col-6">
                <a class="button large secondary cancel-cast">Cancel</a>
            </div>
            <div class="col-6">
                <a class="button large primary update-cast">Update Name</a>
            </div>
        </div>
    </div>
</div>
<div class="abandon-container">
    <div class="abandon">
        <h4>Abandon your masterpiece?</h4>
        <p>Are you sure you want to deprive the world of this cinematic masterpiece? All changes will be lost.</p>
        <div class="row">
            <div class="col-6">
                <a class="button large secondary barebones close-abandon">Cancel</a>
            </div>
            <div class="col-6">
                <a class="button large primary barebones" href="/inspiration">Ok</a>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_Terms")

<div class="image-lightbox">
    <div class="image-container">
        <img src="" alt="" id="final-image">
    </div>
</div>
<div class="loading">
    <div class="loadContain">
        <img src="@Url.Content("~/Images/loading.gif")" alt="" class="loading-spin">
        <!--<div class="spinner">
          <div class="rect1"></div>
          <div class="rect2"></div>
          <div class="rect3"></div>
          <div class="rect4"></div>
          <div class="rect5"></div>
        </div>-->
        <p class="loadingMessage">Fear and Loading in Las Vegas...</p>
    </div>
</div>
<div class="sidebar">
    <a class="closeSidebar"><img src="@Url.Content("~/Images/closeButton.png")" height="30" width="30" alt=""></a>
    <div class="row sidebarTop">
        <div class="large-12 columns">
            <a class="sidebar-back button">Back</a>
            <h2 class="sidebarTitle">Edit Face - <span class="currentSection">Insert an Image</span></h2>
        </div>
    </div>
    <div class="pickInput">
        <div class="input-method webcam-input">
            <div class="icon"></div>
            <h2>Take a Photo</h2>
        </div>
        <div class="divider">
            <img src="@Url.Content("~/Images/divider.png")" height="33" width="132" alt="">
        </div>
        <div class="input-method facebook-input">
            <div class="icon"></div>
            <h2>Choose from Facebook</h2>
        </div>
    </div>
    <div class="yourImages">
        <div class="row">
            <div class="large-12 columns">
                <div class="sidebarLoading">
                    <img src="@Url.Content("~/Images/loading.gif")" alt="" class="loading-spin">
                </div>
                <ul class="photoPicker"></ul>
            </div>
        </div>
    </div>
    <div class="row sidebarButtons">
        <div class="buttonContain">
            <div class="col-6">
                <a href="@Url.Action("Index","Gallery")" class="button large secondary">Cancel</a>
            </div>
            <div class="col-6">
                <a href="/editor.html" class="button large primary">
                    Save
                </a>
            </div>
        </div>
    </div>
</div>
<div class="blackOut"></div>
<div class="container">
    <div class="row">
        <header>
            <a href="/">
                <img src="@Url.Content("~/Images/logo.png")" height="79" width="208" alt="" class="center">
            </a>
            <div class="fbStatus">
                <p>Connected as <span class="myName"></span><a href="@Url.Action("Index", "Home")" class="logOut" onclick="facebookLogOut()">Log Out</a></p>
            </div>
        </header>
    </div>
    <div class="row editorNav">
        <div class="col-6">
            <a class="button large secondary backToInspiration">&#171; Back to Inspiration</a>
        </div>
        <div class="col-6">
            <a class="button large savePoster">Save and Continue &#187;</a>
        </div>
    </div>

    <div class="webcam-contain">
        <div class="takePhoto">
            <h2>Hit SPACE to take a photo</h2>
            <a href="#" class="button large secondary closeWebcam">Cancel</a>
            <span class="webcam-warning">Note: Chrome users may not see preview, but image will still be captured.</span>
        </div>
        <div class="webcam-wrap">
            <div id="webcam"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <div class="panel">
                <div class="steps">
                    <div class="step">
                        <div class="heading">
                            <div class="first line"><h4>1</h4></div>
                            <div class="second line"><h1>Pick Inspiration</h1></div>
                        </div>
                    </div>
                    <div class="step active">
                        <div class="heading">
                            <div class="first line"><h4>2</h4></div>
                            <div class="second line"><h1>Design Your Poster</h1></div>
                        </div>
                        <p>Time to take our templates from 'who' to you. Add your own face. Add your friends. Then try some carefully crafted words to let the whole world know who you are.</p>
                        <p><strong class="for-best-results">For best results, try and use a photo that's well-lit, evenly-exposed, and front-on.</strong></p>
                        <p>Remember to ensure that your work is original and that you comply with our <a href="#" class="terms-of-use">terms of use</a>.</p>
                    </div>
                    <div class="step">
                        <div class="heading">
                            <div class="first line"><h4>3</h4></div>
                            <div class="second line"><h1>Save and Share</h1></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @RenderBody()
    </div>
    <div class="row">
        <div class="col-3">
        </div>
        <div class="col-9 renderDump">

        </div>
    </div>
    <div class="row">
        <div class="col-3">
        </div>
        <div class="col-9 finalDump">

        </div>
    </div>

</div>

@section AddToHead
{
    <link href="@Url.Content("~/Content/jui.css")" rel="stylesheet">
}

@section Scripts
{
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/pointer-fill.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/fb-ck.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/flexslider.js")"></script>

    <!-- Main App -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/app-ck.js")"></script>

    <!-- Editor Scripts -->
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
    <script src="@Url.Content("~/Scripts/html2canvas.js")"></script>
    <script src="@Url.Content("~/Scripts/slider.js")"></script>
    <script src="@Url.Content("~/Scripts/caman.js")"></script>
    <script src="@Url.Content("~/Scripts/scriptcam.min.js")"></script>
    <script src="@Url.Content("~/Scripts/getImage.js")"></script>
    <script src="@Url.Content("~/Scripts/squishy.js")"></script>
    <script src="@Url.Content("~/Scripts/editor.js")"></script>
}

@RenderSection("scripts", required: false)